[build]
  command = "npm run build"
  functions = "./functions"
  publish = "dist/github-user-search"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
